version: '3.8'

services:
  php:
     build: ./php
     image: php82
     volumes:
       - ./html:/var/www/html
     depends_on:
       - mysql
     restart: always
     ports:
      - 3000:80

  mysql:
    ports:
      - 3001:3306
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: home_search_wp
      MYSQL_ROOT_PASSWORD: En2aqskS
      MYSQL_PASSWORD: root
    restart: always
    volumes:
      - home_search_data:/var/lib/mysql
volumes:
  home_search_data:
